/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Enquiry = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'courseInterest' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});
export const Course = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'duration' : IDL.Text,
  'description' : IDL.Text,
  'level' : IDL.Text,
  'category' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
  'getCourseById' : IDL.Func([IDL.Nat], [Course], ['query']),
  'getCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'submitEnquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Enquiry = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'courseInterest' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  const Course = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'duration' : IDL.Text,
    'description' : IDL.Text,
    'level' : IDL.Text,
    'category' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
    'getCourseById' : IDL.Func([IDL.Nat], [Course], ['query']),
    'getCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'submitEnquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };